const Districts = {
  Arusha: ["Arusha", "Arumeru", "Monduli", "Karatu", "Longido", "Ngorongoro"],
  "Dar es Salaam": ["Ilala", "Kigamboni", "Kinondoni", "Temeke", "Ubungo"],
  Dodoma: [
    "Bahi",
    "Chamwino",
    "Kongwa",
    "Mpwapwa",
    "Kondoa",
    "Dodoma",
    "Chemba",
  ],
  Geita: [""],
  Iringa: ["Iringa", "Mufindi", "Kilolo"],
  Kagera: [
    "Bukoba",
    "Biharamulo",
    "Karagwe",
    "Kyerwa",
    "Missenyi",
    "Muleba",
    "Ngara",
  ],
  Katavi: ["Mpanda", "Mlele", "Tanganyika"],
  Kigoma: ["Kibondo", "Kigoma", "Kakonko", "Kasulu", "Uvinza", "Buhigwe"],
  Kilimanjaro: ["Hai", "Moshi", "Mwanga", "Same", "Rombo", "Siha"],
  Lindi: ["Kilwa", "Lindi", "Liwale", "Nachingwea", "Ruangwa"],
  Manyara: ["Babati", "Mbulu", "Hanang", "Kiteto", "Simanjiro"],
  Mara: ["Musoma", "Butiama", "Bunda", "Rorya", "Tarime", "Serengeti"],
  Mbeya: ["Mbeya", "Chunya", "Mbarali", "Rungwe", "Kyela"],
  Morogoro: [
    "Morogoro",
    "Mvomero",
    "Gairo",
    "Kilosa",
    "Kilombero",
    "Ulanga",
    "Malinyi",
  ],
  Mtwara: ["Mtwara", "Newala", "Tandahimba", "Masasi", "Nanyumbu"],
  Mwanza: [
    "Ilemela",
    "Nyamagana",
    "Magu",
    "Misungwi",
    "Kwimba",
    "Sengerema",
    "Ukerewe",
  ],
  Njombe: ["Njombe", "Wanging'ombe", "Makete", "Ludewa"],
  "Pemba North": [""],
  "Pemba South": [""],
  Pwani: [
    "Kibaha",
    "Bagamoyo",
    "Mafia",
    "Kisarawe",
    "Mkuranga",
    "Rufiji",
    "Kibiti",
  ],
  Rukwa: ["Sumbawanga", "Nkasi", "Kalambo"],
  Ruvuma: ["Songea", "Mbinga", "Nyasa", "Tunduru", "Nantumbo"],
  Shinyanga: ["Shinyanga", "Kahama", "Kishapu"],
  Simiyu: ["Bariadi", "Busega", "Itilima", "Maswa", "Meatu"],
  Singida: ["Ikungi", "Iramba", "Manyoni", "Mkalama", "Singida"],
  Songwe: ["Mbozi", "Songwe", "Momba", "Ileje"],
  Tabora: ["Urambo", "Igunga", "Tabora Vijijini", "Kaliua", "Sikonge", "Nzega"],
  Tanga: [
    "Muheza",
    "Pangani",
    "Mkinga",
    "Korogwe",
    "Handeni",
    "Kilindi",
    "Lushoto",
  ],
  "Zanzibar North": [""],
  "Zanzibar South and Central": [""],
  "Zanzibar West": [""],
};

export default Districts;
