const Wards = {
  Arusha: [
    "Baraa",
    "Daraja II",
    "Elerai",
    "Engutoto",
    "Kaloleni",
    "Kati",
    "Kimandolu",
    "Lemara",
    "Levolosi",
    "Moivaro",
    "Moshono",
    "Murriet",
    "Ngarenaro",
    "Olasiti",
    "Olmoti",
    "Oloirien",
    "Osunyai",
    "Sakina",
    "Sekei",
    "Sinon",
    "Sokon I",
    "Sombetini",
    "Terrat",
    "Themi",
    "Unga Ltd",
    //
    "OLTURMET",
    "MWANDET",
    "KISONGO",
    "KIUTU",
    "BWAWANI",
    "OLORIEN",
    "SAMBASHA",
    "SOKON II",
    "OLMOTONYI",
    "OLTUROTO",
    "ILKIDING'A",
    "KIRANYI",
    "KIMNYAK",
    "O'SAMBU",
    "NDURUMA",
    "OLDONYOWAS",
    "MATEVES",
    "OLJORO",
    "LEMANYATA",
    "BANGATA",
    "TARAKWA",
    "OLKOKOLA",
    "MOIVO",
    "ILBORU",
    "MUSA",
    "LAROI",
    "MLANGARINI",
  ],
  Arumeru: [
    "Akheri",
    "Kikatiti",
    "Kikwe",
    "King'ori",
    "Leguruki",
    "Maji ya chai",
    "Makiba",
    "Maroroni",
    "Mbuguni",
    "Ngarenanyuki",
    "Nkoanrua",
    "Nkoaranga",
    "Nkoarisambu",
    "Poli",
    "Seela Sing'isi",
    "Songoro",
    "Usariver",
  ],
  Monduli: [
    "Monduli Mjini",
    "Naalarami",
    "Monduli Juu",
    "Mto wa mbu",
    "Mswakini",
    "Lolksale",
    "Meserani",
    "Lepurko",
    "Migungani",
    "Engutoto",
    "Lashaine",
    "Esilalei",
    "Mfereji",
    "Majengo",
    "Selela",
    "Lemoot",
    "Engaruka",
    "Moita",
    "Makuyuni",
    "Sepeko",
  ],
  Karatu: [],
  Longido: [
    "Sinya",
    "Engarenaibor",
    "Mundarara",
    "Engikaret",
    "Gelai Lumbwa",
    "Namanga",
    "Gelai Merugoi",
    "Ilorienito",
    "Ketumbeine",
    "Noondoto",
    "Mundarara",
    "Kimokouwa",
    "Longido",
    "Matale",
    "Tingatinga",
    "Orbomba",
  ],
  Ngorongoro: [
    "Arash",
    "Endulen",
    "Ololosokwan",
    "Kakesio",
    "Engaresero",
    "Nainokanoka",
    "Kirangi",
    "Sale",
    "Oloipiri",
    "Samunge",
    "Misigyo",
    "Maaloni",
    "Soitsambu",
    "Ngoile",
    "Orgosorok",
    "Alaitolei",
    "Oloirien/Magaiduru",
    "Enguserosambu",
    "Alailelai",
    "Digodigo",
    "Naiyobi",
    "Olbalbal",
    "Pinyinyi",
    "Malambo",
    "Ngorongoro",
    "Piyaya",
    "Eyasi",
    "Oldonyosambu",
  ],
  Ilala: [
    "Bonyokwa",
    "Segerea",
    "Vingunguti",
    "Kinyerezi",
    "Kisukuru",
    "Buguruni",
    "Kimanga",
    "Kitunda",
    "Tabata",
    "Kipawa",
    "Kivule",
    "Liwiti",
    "Gongo la Mboto",
    "Pugu",
    "Zingiziwa",
    "Ukonga",
    "Majohe",
    "Mchikichini",
    "Gerezani",
    "Mzinga",
    "Kipunguni",
    "Pugu Stesheni",
    "Upanga Magharibi",
    "Upanga Mashariki",
    "Kiwalani",
    "Mnyamani",
    "Kivukoni",
    "Msongola",
    "Chanika",
    "Mchafukoge",
    "Jangwani",
    "Buyuni",
    "Minazi Mirefu",
    "Kariakoo",
    "Kisutu",
    "Ilala",
  ],
  Kigamboni: [
    "Kibada",
    "Tungi",
    "Mjimwema",
    "Kigamboni",
    "Kisarawe II",
    "Somangila",
    "Kimbiji",
    "Pemba Mnazi",
  ],
  Kinondoni: [
    "Makongo",
    "Kunduchi",
    "Kunduchi",
    "Hananasif",
    "Mikocheni",
    "Kigogo",
    "Tandale",
    "Mabwepande",
    "Mzimuni",
    "Kawe",
    "Msasani",
    "Ndugumbi",
    "Mbezi juu",
    "Bunju",
    "Wazo",
    "Kijitonyama",
    "Mwananyamala",
    "Makumbusho",
    "Magomeni",
    "Kinondoni",
  ],
  Temeke: [
    "Charambe",
    "Miburani",
    "Kibonde Maji",
    "Tandika",
    "Temeke",
    "Mianzini",
    "Azimio",
    "Sandali",
    "Mtoni",
    "Chang'ombe",
    "Yombo Vituka",
    "Kurasini",
    "Keko",
    "Chamazi",
    "Makangarawe",
    "Buza",
    "Mbagala",
    "Toa Ngoma",
    "Kiburugwa",
    "Kilungule",
    "Kilakala",
    "Kijichi",
  ],
  Ubungo: [
    "Kibamba",
    "Ubungo",
    "Manzese",
    "Goba",
    "Kwembe",
    "Mabibo",
    "Makurumla",
    "Mburahati",
    "Msigani",
    "Makuburi",
    "Mbezi",
    "Sinza",
    "Saranga",
  ],
  Bahi: [],
  Chamwino: [],
  Kongwa: [],
  Mpwapwa: [],
  Kondoa: [],
  Dodoma: [],
  Chemba: [],
  Iringa: [],
  Mufindi: [],
  Kilolo: [],
  Bukoba: [],
  Biharamulo: [],
  Karagwe: [],
  Kyerwa: [],
  Missenyi: [],
  Muleba: [],
  Ngara: [],
  Mpanda: [],
  Mlele: [],
  Tanganyika: [],
  Kibondo: [],
  Kigoma: [],
  Kakonko: [],
  Kasulu: [],
  Uvinza: [],
  Buhigwe: [],
  Hai: [],
  Moshi: [],
  Mwanga: [],
  Same: [],
  Rombo: [],
  Siha: [],
  Kilwa: [],
  Lindi: [],
  Liwale: [],
  Nachingwea: [],
  Ruangwa: [],
  Babati: [],
  Mbulu: [],
  Hanang: [],
  Kiteto: [],
  Simanjiro: [],
  Musoma: [],
  Butiama: [],
  Bunda: [],
  Rorya: [],
  Tarime: [],
  Serengeti: [],
  Mbeya: [],
  Chunya: [],
  Mbarali: [],
  Rungwe: [],
  Kyela: [],
  Morogoro: [],
  Mvomero: [],
  Gairo: [],
  Kilosa: [],
  Kilombero: [],
  Ulanga: [],
  Malinyi: [],
  Mtwara: [],
  Newala: [],
  Tandahimba: [],
  Masasi: [],
  Nanyumbu: [],
  Ilemela: [],
  Nyamagana: [],
  Magu: [],
  Misungwi: [],
  Kwimba: [],
  Sengerema: [],
  Ukerewe: [],
  Njombe: [],
  "Wanging'ombe": [],
  Makete: [],
  Ludewa: [],
  Kibaha: [],
  Bagamoyo: [],
  Mafia: [],
  Kisarawe: [],
  Mkuranga: [],
  Rufiji: [],
  Kibiti: [],
  Sumbawanga: [],
  Nkasi: [],
  Kalambo: [],
  Songea: [],
  Mbinga: [],
  Nyasa: [],
  Tunduru: [],
  Nantumbo: [],
  Shinyanga: [],
  Kahama: [],
  Kishapu: [],
  Bariadi: [],
  Busega: [],
  Itilima: [],
  Maswa: [],
  Meatu: [],
  Ikungi: [],
  Iramba: [],
  Manyoni: [],
  Mkalama: [],
  Singida: [],
  Mbozi: [],
  Songwe: [],
  Momba: [],
  Ileje: [],
  Urambo: [],
  Igunga: [],
  "Tabora Vijijini": [],
  Kaliua: [],
  Sikonge: [],
  Nzega: [],
  Muheza: [],
  Pangani: [],
  Mkinga: [],
  Korogwe: [],
  Handeni: [],
  Kilindi: [],
  Lushoto: [],
};

export default Wards;
